/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.ejercicio5;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.stream.Stream;
import javax.swing.JOptionPane;
import py.com.ejercicio5.entity.Medicamento;
import py.com.ejercicio5.excepciones.PosicionFueraRangoException;

/**
 *
 * @author jose-arco
 */
public class AppListaEstatica extends javax.swing.JFrame {

    /**
     * Creates new form AppListaEstatica
     */
    public AppListaEstatica() {
        leerArchivoMedicamentos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Imprimir desde ultimo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Imprimir desde el inicio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Total de medicamentos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Insertar Medicamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Eliminar un medicamento");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setText("Buscar un medicamento");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem7.setText("Buscar medicamento por indice");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        for(int cont = medicamentos.tamano();cont>0;cont--){
                System.out.println(medicamentos.consultar(cont));
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        for(int cont = 1;cont<=medicamentos.tamano();cont++){
                System.out.println(medicamentos.consultar(cont));
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int totalMedicamentos = 0;
        for(int cont = 1; cont<=medicamentos.tamano(); cont++){
            totalMedicamentos += medicamentos.consultar(cont).getCantidad();
        }
        JOptionPane.showMessageDialog(null, "El total de medicamentos es de :"+totalMedicamentos);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int index = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el indice donde quiere insertar"));
        while(index<1 || medicamentos.tamano() < index){
            index = Integer.parseInt(JOptionPane.showInputDialog("Introduzca de vuelta el indice donde quiere insertar"));
        }
        Medicamento medicamento = new Medicamento();
        String marca = JOptionPane.showInputDialog("Introduzca la marca del medicamento");
        while(marca.isEmpty()){
            marca = JOptionPane.showInputDialog("Introduzca de vuelta la marca del medicamento");
        }
        String modelo = JOptionPane.showInputDialog("Introduzca el modelo del medicamento");
        while(modelo.isEmpty()){
            modelo = JOptionPane.showInputDialog("Introduzca de nuevo el modelo del medicamento");
        }
        Integer cantidad = Integer.parseInt(JOptionPane.showInputDialog("Introduzca la cantidad del medicamento"));
        while(cantidad < 1){
            cantidad = Integer.parseInt(JOptionPane.showInputDialog("Introduzca de nuevo la cantidad del medicamento"));
        }
        String fecha = JOptionPane.showInputDialog("Introduzca la fecha de entrada del medicamento");
        while(fecha.isEmpty()){
            fecha = JOptionPane.showInputDialog("Introduzca de nuevo la fecha de entrada del medicamento");
        }
        medicamento.setCantidad(cantidad);
        medicamento.setFecha(fecha);
        medicamento.setId("00"+index);
        medicamento.setModelo(modelo);
        medicamento.setMarca(marca);
        medicamentos.insertar(medicamento, index);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int index = 0;
        String aux = "";
        while(aux.isEmpty() || Integer.parseInt(aux)<1){
            aux = JOptionPane.showInputDialog("Introduzca el indice del medicamento a eliminar");
        }
        index = Integer.parseInt(aux);
        if(index>0){
            medicamentos.suprimir(index);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        int index = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el indice del medicamento"));
        Medicamento medicamento = null;
        medicamento = medicamentos.consultar(index);
        if(medicamento == null){
            JOptionPane.showMessageDialog(null, "El medicamento no existe");
        }else{
            JOptionPane.showMessageDialog(null,medicamento.toString());
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        int index = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el indice donde del medicamento"));
        Medicamento medicamento = new Medicamento();
        String marca = JOptionPane.showInputDialog("Introduzca la marca del medicamento");
        String modelo = JOptionPane.showInputDialog("Introduzca el modelo del medicamento");
        Integer cantidad = Integer.parseInt(JOptionPane.showInputDialog("Introduzca la cantidad del medicamento"));
        String fecha = JOptionPane.showInputDialog("Introduzca la fecha de entrada del medicamento");
        medicamento.setCantidad(cantidad);
        medicamento.setFecha(fecha);
        medicamento.setId("00"+index);
        medicamento.setModelo(modelo);
        medicamento.setMarca(marca);
        if(medicamentos.buscar(medicamento)>0){
            JOptionPane.showMessageDialog(null, "El medicamento existe");
        }else{
            JOptionPane.showMessageDialog(null, "El medicamento no existe");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppListaEstatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppListaEstatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppListaEstatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppListaEstatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppListaEstatica().setVisible(true);
            }
        });
    }
    
    private static void inicializarMedicamentos(){
        medicamentos = new ListaEstatica<Medicamento>();
        medicamentos.iniciar(countMedicamentos);
    }
    
    /**
     * AQUI LEEMOS EL ARCHIVO Y INICIALIZAMOS LAS VARIABLES DEL VECTOR
     */
    private static void leerArchivoMedicamentos(){
        try{
            fileReader = new FileReader("Medicamentos.txt");
            bufferedReader = new BufferedReader(fileReader);
            String lineaMedicamento = "";
            List<Medicamento> auxMedicamento = new ArrayList<Medicamento>();
            while(lineaMedicamento != null){
                lineaMedicamento = bufferedReader.readLine();
                if(lineaMedicamento != null){
                    auxMedicamento.add(toMedicamento(lineaMedicamento));
                }
            }
            countMedicamentos = auxMedicamento.size();
            inicializarMedicamentos();
            for(Medicamento medicamento: auxMedicamento){
                medicamentos.insertar(medicamento);
            }
            JOptionPane.showMessageDialog(null, "Se cargo los medicamentos");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    
    
    /**
     * LEEMOS LA CADENA DEL MEDICAMENTO Y RETORNAMOS EL MEDICAMENTO
     * @param medicamentoCrudo
     * @return 
     */
    private static Medicamento toMedicamento(String medicamentoCrudo){
        StringTokenizer stringTokenizer = new StringTokenizer(medicamentoCrudo);
        Medicamento medicamento = new Medicamento();
        int cont = 0;
        String dato = "";
        while(stringTokenizer.hasMoreTokens()){
            cont++;
            dato = stringTokenizer.nextToken();
            switch(cont){
                case 1:{
                    medicamento.setId(dato);
                    break;
                }
                case 2:{
                    medicamento.setMarca(dato);
                    break;
                }
                case 3:{
                    medicamento.setModelo(dato);
                    break;
                }
                case 4:{
                    medicamento.setCantidad(Integer.valueOf(dato));
                    break;
                }
                case 5:{
                    medicamento.setFecha(dato);
                }
            }
        }
        return medicamento;
    }
    
    
    private static FileReader fileReader;
    private static BufferedReader bufferedReader;
    private static ListaEstatica<Medicamento> medicamentos;
    private static int countMedicamentos;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
